name: Build
on: workflow_dispatch
jobs:
  # Build Ubuntu
  vm-build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages, create venv, pip install, run Build  
        run: |
          sudo apt-get install -y upx-ucl python3-pip python3-venv && \
          python3 -m venv venv && \
          source venv/bin/activate && \
          pip3 install --upgrade pip wheel setuptools && \
          pip3 install -r requirements.txt && \
          pip3 install pyinstaller sysv-ipc geoip2 && \
          ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-build-ubuntu
          path: |
            *.tar.gz
            *.sha512sum
          if-no-files-found: error

  # Build CentOS 7
  centos-container-job:
      runs-on: ubuntu-latest
      container: centos:7
      steps:
        - uses: actions/checkout@v2
        - name: Install packages, create venv, pip install, run Build  
          run: |
            #yum groupinstall -y "Development Tools" && \
            yum install -y gcc python3-devel python3-pip python3-virtualenv && \
            rpm -i https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/u/ucl-1.03-24.el7.x86_64.rpm && \
            rpm -i https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/u/upx-3.96-9.el7.x86_64.rpm && \
            python3 -m venv venv && \
            source venv/bin/activate && \
            pip3 install --upgrade pip wheel setuptools && \
            pip3 install -r requirements.txt && \
            pip3 install pyinstaller sysv-ipc geoip2 && \
            ./build.sh
        - uses: actions/upload-artifact@v2
          with:
            name: artifact-build-centos
            path: |
              *.tar.gz
              *.sha512sum

