name: Build pywho
on:
  push:
    paths:
    - 'pywho.py'
  workflow_dispatch:

jobs:
  ubuntu-vm-build-job:
    name: Build for Ubuntu 20.04
    #runs-on: ubuntu-latest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install packages, create venv, pip install, run {{ runner_os }} Build  
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m venv venv && \
          . venv/bin/activate && \
          pip3 install --upgrade pip wheel setuptools && \
          pip3 install -r requirements.txt && \
          pip3 install pyinstaller sysv-ipc geoip2 && \
          ./build.sh && \
          mv -f *.tar.gz *.sha512sum bin && \
          git config --global user.email "github-actions[bot]" && \
          git config --global user.name "41898282+github-actions[bot]@users.noreply.github.com" && \
          git add bin && git commit -m "update ubuntu binary" && git push

      # - uses: actions/upload-artifact@v2
      #  with:
      #    name: artifact-build-ubuntu
      #    path: |
      #      *.tar.gz
      #      *.sha512sum
      #    if-no-files-found: error

  
