name: Build Debian
on: workflow_dispatch

jobs:
  # Build for Debian
  debian-container-build-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - debian-release: buster
            python-version: 3.7
          - debian-release: bullseye
            python-version: 3.9
    # container: debian:10
    container: python:${{ matrix.python-version }}-${{ matrix.debian-release }}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages, create venv, pip install, run ${{ matrix.debian-release }} Build
        run: |
          # DEBIAN_FRONTEND=noninteractive apt-get update -y && \
          #apt-get install -y upx-ucl python3-pip python3-venv && \
          apt-get install -y upx-ucl && \
          python3 -m venv venv && \
          pwd; ls -la && \
          . venv/bin/activate && \
          pip3 install --upgrade pip wheel setuptools && \
          pip3 install -r requirements.txt && \
          pip3 install pyinstaller sysv-ipc geoip2 && \
          ./build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: artifact-build-debian-{{ matrix.debian_release }}
          path: |
            *.tar.gz
            *.sha512sum
